### ISSUE TITLE
Spacing on about page.

### ISSUE THREAD

**Issue by perhells** [studieresan/studs2016#2]
https://github.com/studieresan/studs2016/blob/cadc04731ecf742165835f4c7a38fc51013ed8e1/server/views/about/index.jade#L24-L27 causes the text to appear like "If you want to contact us you can send an email to oursales manager Brian Yeor to ourproject leaders Axel Samuelsson and Katja Röös." on the about page.

**Comment by relmgren** [comment]
fixed!
